// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: type/v1/pagination.proto

package typev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination parameters for list requests. Field names and types follow
// https://google.aip.dev/158; the message additionally carries an
// `offset` field for collections where token-based continuation is
// inconvenient (small, slow-changing, or admin-only lists).
// `page_token` and `offset` are mutually exclusive — set at most one.
//
// Request-side only. This message covers the parameters a client sends;
// services define their own list-response shape — by convention a
// repeated items field at position 1 plus a `string next_page_token`
// that callers feed back into `page_token` on the following request.
// There is intentionally no shared `PaginationResponse` here because
// the items-field type and optional total counts vary per service.
//
// `page_size` semantics: zero requests the service-defined default of
// 1000 items. Servers MUST cap it at an implementation-defined maximum
// and MUST return INVALID_ARGUMENT for negative values. The
// NON_EMPTY_DEFAULT annotation signals that the server substitutes a
// concrete non-empty value (1000) when the client leaves the field
// unset.
//
// `page_token` semantics: opaque string minted by the server. Clients
// MUST round-trip it verbatim and MUST NOT decode or synthesise one.
// Servers MAY invalidate tokens at any time (schema migrations,
// snapshot expiry) and SHOULD respond with INVALID_ARGUMENT or a typed
// error rather than silently restarting from the first page.
//
// `offset` semantics: number of items to skip from the start of the
// unpaginated result set. Prefer `page_token` for large or rapidly
// changing collections — `offset` re-scans the result set and is
// subject to drift when items are inserted or deleted between calls.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of items the server should return. Zero requests
	// the service-defined default (1000); negative values yield
	// INVALID_ARGUMENT.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque continuation token returned in a previous list response.
	// Empty (the default) requests the first page. Mutually exclusive
	// with `offset`.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Number of items to skip from the start of the unpaginated result
	// set. Zero (the proto3 default) requests the first page. Mutually
	// exclusive with `page_token`.
	Offset        int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_type_v1_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_type_v1_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_type_v1_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *Pagination) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_type_v1_pagination_proto protoreflect.FileDescriptor

var file_type_v1_pagination_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e, 0x61,
	0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x65, 0x0a, 0x0a, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x42, 0x03, 0xe0, 0x41, 0x07, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x42, 0x48, 0x0a, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74,
	0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x30,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73,
	0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67,
	0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_type_v1_pagination_proto_rawDescOnce sync.Once
	file_type_v1_pagination_proto_rawDescData []byte
)

func file_type_v1_pagination_proto_rawDescGZIP() []byte {
	file_type_v1_pagination_proto_rawDescOnce.Do(func() {
		file_type_v1_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_v1_pagination_proto_rawDesc), len(file_type_v1_pagination_proto_rawDesc)))
	})
	return file_type_v1_pagination_proto_rawDescData
}

var file_type_v1_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_type_v1_pagination_proto_goTypes = []any{
	(*Pagination)(nil), // 0: io.altessa.type.v1.Pagination
}
var file_type_v1_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_type_v1_pagination_proto_init() }
func file_type_v1_pagination_proto_init() {
	if File_type_v1_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_v1_pagination_proto_rawDesc), len(file_type_v1_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_v1_pagination_proto_goTypes,
		DependencyIndexes: file_type_v1_pagination_proto_depIdxs,
		MessageInfos:      file_type_v1_pagination_proto_msgTypes,
	}.Build()
	File_type_v1_pagination_proto = out.File
	file_type_v1_pagination_proto_goTypes = nil
	file_type_v1_pagination_proto_depIdxs = nil
}
