// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: type/v1/sort_direction.proto

package typev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Ordering direction for list / search responses. Typically appears in
// a list request next to a service-specific sort-field selector, e.g.
//
//	message ListUsersRequest {
//	  string sort_by = 1;             // service-defined field name
//	  SortDirection direction = 2;
//	  Pagination pagination = 3;
//	}
//
// For multi-key ordering or per-field direction, services define their
// own richer sort message — this enum stays a single-direction
// primitive on purpose.
//
// Zero value: unlike most enums in this package, `SortDirection` does
// not have an `_UNSPECIFIED` zero value. `SORT_DIRECTION_ASC = 0` is
// the natural default (matches SQL `ORDER BY` without `DESC`), so a
// distinct sentinel would add noise without information. This is the
// only exception in `type/v1` (see `buf.yaml` for the lint waiver).
//
// Stability (AIP-180): closed and frozen at v1. There are only two
// meaningful directions for a single sort key; consumers MAY assume
// the value set will not grow.
type SortDirection int32

const (
	// Ascending: A→Z, 0→9, oldest first. This is the default.
	SortDirection_SORT_DIRECTION_ASC SortDirection = 0
	// Descending: Z→A, 9→0, newest first.
	SortDirection_SORT_DIRECTION_DESC SortDirection = 1
)

// Enum value maps for SortDirection.
var (
	SortDirection_name = map[int32]string{
		0: "SORT_DIRECTION_ASC",
		1: "SORT_DIRECTION_DESC",
	}
	SortDirection_value = map[string]int32{
		"SORT_DIRECTION_ASC":  0,
		"SORT_DIRECTION_DESC": 1,
	}
)

func (x SortDirection) Enum() *SortDirection {
	p := new(SortDirection)
	*p = x
	return p
}

func (x SortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_type_v1_sort_direction_proto_enumTypes[0].Descriptor()
}

func (SortDirection) Type() protoreflect.EnumType {
	return &file_type_v1_sort_direction_proto_enumTypes[0]
}

func (x SortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortDirection.Descriptor instead.
func (SortDirection) EnumDescriptor() ([]byte, []int) {
	return file_type_v1_sort_direction_proto_rawDescGZIP(), []int{0}
}

var File_type_v1_sort_direction_proto protoreflect.FileDescriptor

var file_type_v1_sort_direction_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x76, 0x31, 0x2a, 0x40, 0x0a, 0x0d, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x53, 0x43, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x53,
	0x4f, 0x52, 0x54, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45,
	0x53, 0x43, 0x10, 0x01, 0x42, 0x48, 0x0a, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73,
	0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61,
	0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_type_v1_sort_direction_proto_rawDescOnce sync.Once
	file_type_v1_sort_direction_proto_rawDescData []byte
)

func file_type_v1_sort_direction_proto_rawDescGZIP() []byte {
	file_type_v1_sort_direction_proto_rawDescOnce.Do(func() {
		file_type_v1_sort_direction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_v1_sort_direction_proto_rawDesc), len(file_type_v1_sort_direction_proto_rawDesc)))
	})
	return file_type_v1_sort_direction_proto_rawDescData
}

var file_type_v1_sort_direction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_type_v1_sort_direction_proto_goTypes = []any{
	(SortDirection)(0), // 0: io.altessa.type.v1.SortDirection
}
var file_type_v1_sort_direction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_type_v1_sort_direction_proto_init() }
func file_type_v1_sort_direction_proto_init() {
	if File_type_v1_sort_direction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_v1_sort_direction_proto_rawDesc), len(file_type_v1_sort_direction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_type_v1_sort_direction_proto_goTypes,
		DependencyIndexes: file_type_v1_sort_direction_proto_depIdxs,
		EnumInfos:         file_type_v1_sort_direction_proto_enumTypes,
	}.Build()
	File_type_v1_sort_direction_proto = out.File
	file_type_v1_sort_direction_proto_goTypes = nil
	file_type_v1_sort_direction_proto_depIdxs = nil
}
