// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/serviceinfo/v1/serviceinfo_service.proto

package serviceinfov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for the `GetServiceInfo` method. `ServiceInfo` is a per-connection
// singleton — the instance answering the call — so there is no `name` to
// address. The message is intentionally empty for now and exists (instead
// of `google.protobuf.Empty`) so read options such as a
// `google.protobuf.FieldMask` can be added later without changing the RPC
// signature.
type GetServiceInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoRequest) Reset() {
	*x = GetServiceInfoRequest{}
	mi := &file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoRequest) ProtoMessage() {}

func (x *GetServiceInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServiceInfoRequest) Descriptor() ([]byte, []int) {
	return file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescGZIP(), []int{0}
}

// Response for the `GetServiceInfo` method: a wrapper around the
// `ServiceInfo` snapshot. A dedicated response message (rather than
// returning `ServiceInfo` directly) leaves room to add sibling fields
// later without a breaking change.
type GetServiceInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Runtime information for the instance handling the call.
	ServiceInfo   *ServiceInfo `protobuf:"bytes,1,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceInfoResponse) Reset() {
	*x = GetServiceInfoResponse{}
	mi := &file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceInfoResponse) ProtoMessage() {}

func (x *GetServiceInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServiceInfoResponse) Descriptor() ([]byte, []int) {
	return file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetServiceInfoResponse) GetServiceInfo() *ServiceInfo {
	if x != nil {
		return x.ServiceInfo
	}
	return nil
}

var File_io_altessa_serviceinfo_v1_serviceinfo_service_proto protoreflect.FileDescriptor

var file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDesc = string([]byte{
	0x0a, 0x33, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73,
	0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31,
	0x1a, 0x2b, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x17, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x63, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65,
	0x73, 0x73, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x8b, 0x01, 0x0a, 0x12,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x75, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73,
	0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65,
	0x73, 0x73, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x68, 0x0a, 0x19, 0x69, 0x6f, 0x2e,
	0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69,
	0x6e, 0x66, 0x6f, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x49, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61,
	0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69, 0x6e,
	0x66, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x69, 0x6e, 0x66,
	0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescOnce sync.Once
	file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescData []byte
)

func file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescGZIP() []byte {
	file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescOnce.Do(func() {
		file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDesc), len(file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDesc)))
	})
	return file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDescData
}

var file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_goTypes = []any{
	(*GetServiceInfoRequest)(nil),  // 0: io.altessa.serviceinfo.v1.GetServiceInfoRequest
	(*GetServiceInfoResponse)(nil), // 1: io.altessa.serviceinfo.v1.GetServiceInfoResponse
	(*ServiceInfo)(nil),            // 2: io.altessa.serviceinfo.v1.ServiceInfo
}
var file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_depIdxs = []int32{
	2, // 0: io.altessa.serviceinfo.v1.GetServiceInfoResponse.service_info:type_name -> io.altessa.serviceinfo.v1.ServiceInfo
	0, // 1: io.altessa.serviceinfo.v1.ServiceInfoService.GetServiceInfo:input_type -> io.altessa.serviceinfo.v1.GetServiceInfoRequest
	1, // 2: io.altessa.serviceinfo.v1.ServiceInfoService.GetServiceInfo:output_type -> io.altessa.serviceinfo.v1.GetServiceInfoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_init() }
func file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_init() {
	if File_io_altessa_serviceinfo_v1_serviceinfo_service_proto != nil {
		return
	}
	file_io_altessa_serviceinfo_v1_serviceinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDesc), len(file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_goTypes,
		DependencyIndexes: file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_depIdxs,
		MessageInfos:      file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_msgTypes,
	}.Build()
	File_io_altessa_serviceinfo_v1_serviceinfo_service_proto = out.File
	file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_goTypes = nil
	file_io_altessa_serviceinfo_v1_serviceinfo_service_proto_depIdxs = nil
}
