// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: badrequest/v1/badrequest.proto

package badrequestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines a general error structure for requests that are malformed or contain invalid data.
// It typically includes a list of specific field violations that caused the request to be rejected.
// This message is often used as a detail payload for `google.rpc.Status` when the error code is `INVALID_ARGUMENT`.
type BadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of individual field violations that contributed to the bad request.
	FieldViolations []*FieldViolation `protobuf:"bytes,1,rep,name=field_violations,json=fieldViolations" json:"field_violations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BadRequest) Reset() {
	*x = BadRequest{}
	mi := &file_badrequest_v1_badrequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadRequest) ProtoMessage() {}

func (x *BadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_badrequest_v1_badrequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadRequest.ProtoReflect.Descriptor instead.
func (*BadRequest) Descriptor() ([]byte, []int) {
	return file_badrequest_v1_badrequest_proto_rawDescGZIP(), []int{0}
}

func (x *BadRequest) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

// Defines a specific issue with a single field in the request message.
// It provides details about which field was problematic and why.
type FieldViolation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dot-separated path to the field that caused the violation.
	// For example, "user.address.street" or "items[2].name".
	FieldPath *string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath" json:"field_path,omitempty"`
	// Human-readable message describing the violation.
	// This should be specific to the field and the error condition.
	Message *string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// Application-specific error code or identifier for this type of violation.
	// This can be used by clients for programmatic error handling.
	Code *string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	// Structured representation of the path to the field that caused the violation.
	// This provides more detailed information than `field_path` and can be used for
	// more precise error handling or display.
	FieldPathComponents []*FieldPathComponent `protobuf:"bytes,4,rep,name=field_path_components,json=fieldPathComponents" json:"field_path_components,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_badrequest_v1_badrequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_badrequest_v1_badrequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_badrequest_v1_badrequest_proto_rawDescGZIP(), []int{1}
}

func (x *FieldViolation) GetFieldPath() string {
	if x != nil && x.FieldPath != nil {
		return *x.FieldPath
	}
	return ""
}

func (x *FieldViolation) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *FieldViolation) GetCode() string {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return ""
}

func (x *FieldViolation) GetFieldPathComponents() []*FieldPathComponent {
	if x != nil {
		return x.FieldPathComponents
	}
	return nil
}

// Defines a single segment in the path to a violated field.
// It provides details about the field name, number, type, and, if applicable, its index in a repeated field or its key in a map.
type FieldPathComponent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Field number as defined in the .proto file.
	Number *int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	// Name of the field as defined in the .proto file.
	Name *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// Data type of the field.
	Type *descriptorpb.FieldDescriptorProto_Type `protobuf:"varint,3,opt,name=type,enum=google.protobuf.FieldDescriptorProto_Type" json:"type,omitempty"`
	// For map fields, specifies the data type of the map keys.
	MapKeyType *descriptorpb.FieldDescriptorProto_Type `protobuf:"varint,4,opt,name=map_key_type,json=mapKeyType,enum=google.protobuf.FieldDescriptorProto_Type" json:"map_key_type,omitempty"`
	// For map fields, specifies the data type of the map values.
	MapValueType *descriptorpb.FieldDescriptorProto_Type `protobuf:"varint,5,opt,name=map_value_type,json=mapValueType,enum=google.protobuf.FieldDescriptorProto_Type" json:"map_value_type,omitempty"`
	// Indicates whether the field is a repeated field (i.e., an array or list).
	IsRepeated *bool `protobuf:"varint,6,opt,name=is_repeated,json=isRepeated" json:"is_repeated,omitempty"`
	// For repeated fields, the 0-based index of the element that caused the violation.
	RepeatedIndex *uint64 `protobuf:"varint,7,opt,name=repeated_index,json=repeatedIndex" json:"repeated_index,omitempty"`
	// If the field is a map, this `oneof` specifies the key of the map entry that caused the violation.
	// Only one of the `key` fields will be set, corresponding to the actual type of the map key.
	//
	// Types that are valid to be assigned to MapKey:
	//
	//	*FieldPathComponent_Index
	//	*FieldPathComponent_BoolKey
	//	*FieldPathComponent_IntKey
	//	*FieldPathComponent_UintKey
	//	*FieldPathComponent_StringKey
	MapKey        isFieldPathComponent_MapKey `protobuf_oneof:"map_key"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldPathComponent) Reset() {
	*x = FieldPathComponent{}
	mi := &file_badrequest_v1_badrequest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldPathComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldPathComponent) ProtoMessage() {}

func (x *FieldPathComponent) ProtoReflect() protoreflect.Message {
	mi := &file_badrequest_v1_badrequest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldPathComponent.ProtoReflect.Descriptor instead.
func (*FieldPathComponent) Descriptor() ([]byte, []int) {
	return file_badrequest_v1_badrequest_proto_rawDescGZIP(), []int{2}
}

func (x *FieldPathComponent) GetNumber() int32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *FieldPathComponent) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FieldPathComponent) GetType() descriptorpb.FieldDescriptorProto_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return descriptorpb.FieldDescriptorProto_Type(1)
}

func (x *FieldPathComponent) GetMapKeyType() descriptorpb.FieldDescriptorProto_Type {
	if x != nil && x.MapKeyType != nil {
		return *x.MapKeyType
	}
	return descriptorpb.FieldDescriptorProto_Type(1)
}

func (x *FieldPathComponent) GetMapValueType() descriptorpb.FieldDescriptorProto_Type {
	if x != nil && x.MapValueType != nil {
		return *x.MapValueType
	}
	return descriptorpb.FieldDescriptorProto_Type(1)
}

func (x *FieldPathComponent) GetIsRepeated() bool {
	if x != nil && x.IsRepeated != nil {
		return *x.IsRepeated
	}
	return false
}

func (x *FieldPathComponent) GetRepeatedIndex() uint64 {
	if x != nil && x.RepeatedIndex != nil {
		return *x.RepeatedIndex
	}
	return 0
}

func (x *FieldPathComponent) GetMapKey() isFieldPathComponent_MapKey {
	if x != nil {
		return x.MapKey
	}
	return nil
}

func (x *FieldPathComponent) GetIndex() uint64 {
	if x != nil {
		if x, ok := x.MapKey.(*FieldPathComponent_Index); ok {
			return x.Index
		}
	}
	return 0
}

func (x *FieldPathComponent) GetBoolKey() bool {
	if x != nil {
		if x, ok := x.MapKey.(*FieldPathComponent_BoolKey); ok {
			return x.BoolKey
		}
	}
	return false
}

func (x *FieldPathComponent) GetIntKey() int64 {
	if x != nil {
		if x, ok := x.MapKey.(*FieldPathComponent_IntKey); ok {
			return x.IntKey
		}
	}
	return 0
}

func (x *FieldPathComponent) GetUintKey() uint64 {
	if x != nil {
		if x, ok := x.MapKey.(*FieldPathComponent_UintKey); ok {
			return x.UintKey
		}
	}
	return 0
}

func (x *FieldPathComponent) GetStringKey() string {
	if x != nil {
		if x, ok := x.MapKey.(*FieldPathComponent_StringKey); ok {
			return x.StringKey
		}
	}
	return ""
}

type isFieldPathComponent_MapKey interface {
	isFieldPathComponent_MapKey()
}

type FieldPathComponent_Index struct {
	// The index if the map key is treated as an array index (less common for proto maps).
	Index uint64 `protobuf:"varint,8,opt,name=index,oneof"`
}

type FieldPathComponent_BoolKey struct {
	// The map key, if its type is `bool`.
	BoolKey bool `protobuf:"varint,9,opt,name=bool_key,json=boolKey,oneof"`
}

type FieldPathComponent_IntKey struct {
	// The map key, if its type is `int32`, `int64`, `sint32`, `sint64`, `sfixed32`, or `sfixed64`.
	IntKey int64 `protobuf:"varint,10,opt,name=int_key,json=intKey,oneof"`
}

type FieldPathComponent_UintKey struct {
	// The map key, if its type is `uint32`, `uint64`, `fixed32`, or `fixed64`.
	UintKey uint64 `protobuf:"varint,11,opt,name=uint_key,json=uintKey,oneof"`
}

type FieldPathComponent_StringKey struct {
	// The map key, if its type is `string`.
	StringKey string `protobuf:"bytes,12,opt,name=string_key,json=stringKey,oneof"`
}

func (*FieldPathComponent_Index) isFieldPathComponent_MapKey() {}

func (*FieldPathComponent_BoolKey) isFieldPathComponent_MapKey() {}

func (*FieldPathComponent_IntKey) isFieldPathComponent_MapKey() {}

func (*FieldPathComponent_UintKey) isFieldPathComponent_MapKey() {}

func (*FieldPathComponent_StringKey) isFieldPathComponent_MapKey() {}

var File_badrequest_v1_badrequest_proto protoreflect.FileDescriptor

var file_badrequest_v1_badrequest_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x62, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x62, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x18, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x62, 0x61, 0x64,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x0a,
	0x42, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a, 0x10, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x5f, 0x76, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73,
	0x61, 0x2e, 0x62, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0xbf, 0x01, 0x0a, 0x0e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x56, 0x69, 0x6f, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74,
	0x68, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x60, 0x0a, 0x15, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c,
	0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x62, 0x61, 0x64, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50,
	0x61, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x13, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x73, 0x22, 0x81, 0x04, 0x0a, 0x12, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x50, 0x61, 0x74, 0x68, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x4c, 0x0a, 0x0c, 0x6d, 0x61, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x6d, 0x61, 0x70, 0x4b, 0x65, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x6d, 0x61, 0x70, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x6d, 0x61, 0x70, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x70,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x08, 0x62, 0x6f, 0x6f, 0x6c, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x4b, 0x65,
	0x79, 0x12, 0x19, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x69, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x08,
	0x75, 0x69, 0x6e, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00,
	0x52, 0x07, 0x75, 0x69, 0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4b, 0x65, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x61,
	0x70, 0x5f, 0x6b, 0x65, 0x79, 0x42, 0x5a, 0x0a, 0x18, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65,
	0x73, 0x73, 0x61, 0x2e, 0x62, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x62, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x61, 0x64, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x76,
	0x31,
})

var (
	file_badrequest_v1_badrequest_proto_rawDescOnce sync.Once
	file_badrequest_v1_badrequest_proto_rawDescData []byte
)

func file_badrequest_v1_badrequest_proto_rawDescGZIP() []byte {
	file_badrequest_v1_badrequest_proto_rawDescOnce.Do(func() {
		file_badrequest_v1_badrequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badrequest_v1_badrequest_proto_rawDesc), len(file_badrequest_v1_badrequest_proto_rawDesc)))
	})
	return file_badrequest_v1_badrequest_proto_rawDescData
}

var file_badrequest_v1_badrequest_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_badrequest_v1_badrequest_proto_goTypes = []any{
	(*BadRequest)(nil),                          // 0: io.altessa.badrequest.v1.BadRequest
	(*FieldViolation)(nil),                      // 1: io.altessa.badrequest.v1.FieldViolation
	(*FieldPathComponent)(nil),                  // 2: io.altessa.badrequest.v1.FieldPathComponent
	(descriptorpb.FieldDescriptorProto_Type)(0), // 3: google.protobuf.FieldDescriptorProto.Type
}
var file_badrequest_v1_badrequest_proto_depIdxs = []int32{
	1, // 0: io.altessa.badrequest.v1.BadRequest.field_violations:type_name -> io.altessa.badrequest.v1.FieldViolation
	2, // 1: io.altessa.badrequest.v1.FieldViolation.field_path_components:type_name -> io.altessa.badrequest.v1.FieldPathComponent
	3, // 2: io.altessa.badrequest.v1.FieldPathComponent.type:type_name -> google.protobuf.FieldDescriptorProto.Type
	3, // 3: io.altessa.badrequest.v1.FieldPathComponent.map_key_type:type_name -> google.protobuf.FieldDescriptorProto.Type
	3, // 4: io.altessa.badrequest.v1.FieldPathComponent.map_value_type:type_name -> google.protobuf.FieldDescriptorProto.Type
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_badrequest_v1_badrequest_proto_init() }
func file_badrequest_v1_badrequest_proto_init() {
	if File_badrequest_v1_badrequest_proto != nil {
		return
	}
	file_badrequest_v1_badrequest_proto_msgTypes[2].OneofWrappers = []any{
		(*FieldPathComponent_Index)(nil),
		(*FieldPathComponent_BoolKey)(nil),
		(*FieldPathComponent_IntKey)(nil),
		(*FieldPathComponent_UintKey)(nil),
		(*FieldPathComponent_StringKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badrequest_v1_badrequest_proto_rawDesc), len(file_badrequest_v1_badrequest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_badrequest_v1_badrequest_proto_goTypes,
		DependencyIndexes: file_badrequest_v1_badrequest_proto_depIdxs,
		MessageInfos:      file_badrequest_v1_badrequest_proto_msgTypes,
	}.Build()
	File_badrequest_v1_badrequest_proto = out.File
	file_badrequest_v1_badrequest_proto_goTypes = nil
	file_badrequest_v1_badrequest_proto_depIdxs = nil
}
