// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: serviceinfo/v1/serviceinfo_service.proto

package serviceinfov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceInfoService_Get_FullMethodName = "/io.altessa.serviceinfo.v1.ServiceInfoService/Get"
)

// ServiceInfoServiceClient is the client API for ServiceInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provides runtime information about the service instance.
type ServiceInfoServiceClient interface {
	// Retrieves service metadata including version and build information.
	Get(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceInfo, error)
}

type serviceInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceInfoServiceClient(cc grpc.ClientConnInterface) ServiceInfoServiceClient {
	return &serviceInfoServiceClient{cc}
}

func (c *serviceInfoServiceClient) Get(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServiceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceInfo)
	err := c.cc.Invoke(ctx, ServiceInfoService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceInfoServiceServer is the server API for ServiceInfoService service.
// All implementations must embed UnimplementedServiceInfoServiceServer
// for forward compatibility.
//
// Provides runtime information about the service instance.
type ServiceInfoServiceServer interface {
	// Retrieves service metadata including version and build information.
	Get(context.Context, *emptypb.Empty) (*ServiceInfo, error)
	mustEmbedUnimplementedServiceInfoServiceServer()
}

// UnimplementedServiceInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceInfoServiceServer struct{}

func (UnimplementedServiceInfoServiceServer) Get(context.Context, *emptypb.Empty) (*ServiceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServiceInfoServiceServer) mustEmbedUnimplementedServiceInfoServiceServer() {}
func (UnimplementedServiceInfoServiceServer) testEmbeddedByValue()                            {}

// UnsafeServiceInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceInfoServiceServer will
// result in compilation errors.
type UnsafeServiceInfoServiceServer interface {
	mustEmbedUnimplementedServiceInfoServiceServer()
}

func RegisterServiceInfoServiceServer(s grpc.ServiceRegistrar, srv ServiceInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceInfoService_ServiceDesc, srv)
}

func _ServiceInfoService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceInfoServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceInfoService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceInfoServiceServer).Get(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceInfoService_ServiceDesc is the grpc.ServiceDesc for ServiceInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.altessa.serviceinfo.v1.ServiceInfoService",
	HandlerType: (*ServiceInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ServiceInfoService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceinfo/v1/serviceinfo_service.proto",
}
