// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: serviceinfo/v1/serviceinfo_service.proto

package serviceinfov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_serviceinfo_v1_serviceinfo_service_proto protoreflect.FileDescriptor

const file_serviceinfo_v1_serviceinfo_service_proto_rawDesc = "" +
	"\n" +
	"(serviceinfo/v1/serviceinfo_service.proto\x12\x19io.altessa.serviceinfo.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a serviceinfo/v1/serviceinfo.proto2[\n" +
	"\x12ServiceInfoService\x12E\n" +
	"\x03Get\x12\x16.google.protobuf.Empty\x1a&.io.altessa.serviceinfo.v1.ServiceInfoB]\n" +
	"\x19io.altessa.serviceinfo.v1P\x01Z>github.com/altessa-s/proto-gen-go/serviceinfo/v1;serviceinfov1b\x06proto3"

var file_serviceinfo_v1_serviceinfo_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
	(*ServiceInfo)(nil),   // 1: io.altessa.serviceinfo.v1.ServiceInfo
}
var file_serviceinfo_v1_serviceinfo_service_proto_depIdxs = []int32{
	0, // 0: io.altessa.serviceinfo.v1.ServiceInfoService.Get:input_type -> google.protobuf.Empty
	1, // 1: io.altessa.serviceinfo.v1.ServiceInfoService.Get:output_type -> io.altessa.serviceinfo.v1.ServiceInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_serviceinfo_v1_serviceinfo_service_proto_init() }
func file_serviceinfo_v1_serviceinfo_service_proto_init() {
	if File_serviceinfo_v1_serviceinfo_service_proto != nil {
		return
	}
	file_serviceinfo_v1_serviceinfo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviceinfo_v1_serviceinfo_service_proto_rawDesc), len(file_serviceinfo_v1_serviceinfo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviceinfo_v1_serviceinfo_service_proto_goTypes,
		DependencyIndexes: file_serviceinfo_v1_serviceinfo_service_proto_depIdxs,
	}.Build()
	File_serviceinfo_v1_serviceinfo_service_proto = out.File
	file_serviceinfo_v1_serviceinfo_service_proto_goTypes = nil
	file_serviceinfo_v1_serviceinfo_service_proto_depIdxs = nil
}
