// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: serviceinfo/v1/serviceinfo.proto

package serviceinfov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines detailed information about a running service instance.
// It includes identification, versioning, build details, leadership status, and other metadata.
type ServiceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The canonical name of the service (e.g., "user-service", "billing-api").
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Human-readable description of the service and its purpose.
	ServiceDescription *string `protobuf:"bytes,2,opt,name=service_description,json=serviceDescription,proto3,oneof" json:"service_description,omitempty"`
	// Unique identifier for this specific instance of the service (e.g., a UUID or hostname-pid).
	ServiceId *string `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3,oneof" json:"service_id,omitempty"`
	// Indicates whether this service instance is currently the leader in a distributed system.
	// True if this instance is the leader, false otherwise.
	IsLeader bool `protobuf:"varint,4,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	// The full version string of the service (e.g., "1.2.3-alpha+build.123").
	// This may include semantic version, pre-release, and build metadata.
	FullVersion string `protobuf:"bytes,5,opt,name=full_version,json=fullVersion,proto3" json:"full_version,omitempty"`
	// The structured semantic version of the service.
	SemanticVersion *ServiceInfo_SemanticVersion `protobuf:"bytes,6,opt,name=semantic_version,json=semanticVersion,proto3" json:"semantic_version,omitempty"`
	// The timestamp indicating when the service binary was built.
	// Human-readable timestamp representation (e.g., "2025-01-19T15:30:45Z").
	BuildTime string `protobuf:"bytes,7,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	// Name of the source code branch from which this service instance was built (e.g., "main", "develop").
	Branch *string `protobuf:"bytes,8,opt,name=branch,proto3,oneof" json:"branch,omitempty"`
	// Full Git commit hash (SHA) of the source code revision from which this service instance was built.
	Commit *string `protobuf:"bytes,9,opt,name=commit,proto3,oneof" json:"commit,omitempty"`
	// Build tags or flags used during the compilation of the service.
	BuildTags *string `protobuf:"bytes,10,opt,name=build_tags,json=buildTags,proto3,oneof" json:"build_tags,omitempty"`
	// A collection of key-value pairs for additional, arbitrary metadata about the service instance.
	// Keys and values are strings. Maximum 100 entries allowed.
	Metadata map[string]string `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Version of the Protobuf package or definitions that this service was compiled against.
	ProtoVersion *string `protobuf:"bytes,12,opt,name=proto_version,json=protoVersion,proto3,oneof" json:"proto_version,omitempty"`
	// Identifier of the current leader instance if this node is not the leader.
	// This is useful for clients to discover the active leader.
	LeaderId *string `protobuf:"bytes,13,opt,name=leader_id,json=leaderId,proto3,oneof" json:"leader_id,omitempty"`
	// The timestamp when the service instance was started.
	// Human-readable timestamp representation in RFC 3339 format (e.g., "2025-12-18T10:15:30Z").
	StartTime *string `protobuf:"bytes,14,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	// The number of seconds the service has been running since startup.
	// Calculated dynamically on each request as the difference between current time and start_time.
	Uptime        *uint64 `protobuf:"varint,15,opt,name=uptime,proto3,oneof" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_serviceinfo_v1_serviceinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_serviceinfo_v1_serviceinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_serviceinfo_v1_serviceinfo_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceInfo) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceInfo) GetServiceDescription() string {
	if x != nil && x.ServiceDescription != nil {
		return *x.ServiceDescription
	}
	return ""
}

func (x *ServiceInfo) GetServiceId() string {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return ""
}

func (x *ServiceInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *ServiceInfo) GetFullVersion() string {
	if x != nil {
		return x.FullVersion
	}
	return ""
}

func (x *ServiceInfo) GetSemanticVersion() *ServiceInfo_SemanticVersion {
	if x != nil {
		return x.SemanticVersion
	}
	return nil
}

func (x *ServiceInfo) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *ServiceInfo) GetBranch() string {
	if x != nil && x.Branch != nil {
		return *x.Branch
	}
	return ""
}

func (x *ServiceInfo) GetCommit() string {
	if x != nil && x.Commit != nil {
		return *x.Commit
	}
	return ""
}

func (x *ServiceInfo) GetBuildTags() string {
	if x != nil && x.BuildTags != nil {
		return *x.BuildTags
	}
	return ""
}

func (x *ServiceInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServiceInfo) GetProtoVersion() string {
	if x != nil && x.ProtoVersion != nil {
		return *x.ProtoVersion
	}
	return ""
}

func (x *ServiceInfo) GetLeaderId() string {
	if x != nil && x.LeaderId != nil {
		return *x.LeaderId
	}
	return ""
}

func (x *ServiceInfo) GetStartTime() string {
	if x != nil && x.StartTime != nil {
		return *x.StartTime
	}
	return ""
}

func (x *ServiceInfo) GetUptime() uint64 {
	if x != nil && x.Uptime != nil {
		return *x.Uptime
	}
	return 0
}

// Defines a version conforming to the Semantic Versioning 2.0.0 specification (semver.org).
type ServiceInfo_SemanticVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The MAJOR version, incremented for incompatible API changes.
	Major uint32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// The MINOR version, incremented for adding functionality in a backward-compatible manner.
	Minor uint32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// The PATCH version, incremented for backward-compatible bug fixes.
	Patch uint32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	// Pre-release identifier (e.g., "alpha", "beta.1").
	// A series of dot-separated identifiers immediately following the patch version.
	PreRelease    *string `protobuf:"bytes,4,opt,name=pre_release,json=preRelease,proto3,oneof" json:"pre_release,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo_SemanticVersion) Reset() {
	*x = ServiceInfo_SemanticVersion{}
	mi := &file_serviceinfo_v1_serviceinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo_SemanticVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo_SemanticVersion) ProtoMessage() {}

func (x *ServiceInfo_SemanticVersion) ProtoReflect() protoreflect.Message {
	mi := &file_serviceinfo_v1_serviceinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo_SemanticVersion.ProtoReflect.Descriptor instead.
func (*ServiceInfo_SemanticVersion) Descriptor() ([]byte, []int) {
	return file_serviceinfo_v1_serviceinfo_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceInfo_SemanticVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ServiceInfo_SemanticVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *ServiceInfo_SemanticVersion) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *ServiceInfo_SemanticVersion) GetPreRelease() string {
	if x != nil && x.PreRelease != nil {
		return *x.PreRelease
	}
	return ""
}

var File_serviceinfo_v1_serviceinfo_proto protoreflect.FileDescriptor

const file_serviceinfo_v1_serviceinfo_proto_rawDesc = "" +
	"\n" +
	" serviceinfo/v1/serviceinfo.proto\x12\x19io.altessa.serviceinfo.v1\"\xd8\a\n" +
	"\vServiceInfo\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x124\n" +
	"\x13service_description\x18\x02 \x01(\tH\x00R\x12serviceDescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tH\x01R\tserviceId\x88\x01\x01\x12\x1b\n" +
	"\tis_leader\x18\x04 \x01(\bR\bisLeader\x12!\n" +
	"\ffull_version\x18\x05 \x01(\tR\vfullVersion\x12a\n" +
	"\x10semantic_version\x18\x06 \x01(\v26.io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersionR\x0fsemanticVersion\x12\x1d\n" +
	"\n" +
	"build_time\x18\a \x01(\tR\tbuildTime\x12\x1b\n" +
	"\x06branch\x18\b \x01(\tH\x02R\x06branch\x88\x01\x01\x12\x1b\n" +
	"\x06commit\x18\t \x01(\tH\x03R\x06commit\x88\x01\x01\x12\"\n" +
	"\n" +
	"build_tags\x18\n" +
	" \x01(\tH\x04R\tbuildTags\x88\x01\x01\x12P\n" +
	"\bmetadata\x18\v \x03(\v24.io.altessa.serviceinfo.v1.ServiceInfo.MetadataEntryR\bmetadata\x12(\n" +
	"\rproto_version\x18\f \x01(\tH\x05R\fprotoVersion\x88\x01\x01\x12 \n" +
	"\tleader_id\x18\r \x01(\tH\x06R\bleaderId\x88\x01\x01\x12\"\n" +
	"\n" +
	"start_time\x18\x0e \x01(\tH\aR\tstartTime\x88\x01\x01\x12\x1b\n" +
	"\x06uptime\x18\x0f \x01(\x04H\bR\x06uptime\x88\x01\x01\x1a\x89\x01\n" +
	"\x0fSemanticVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\x12$\n" +
	"\vpre_release\x18\x04 \x01(\tH\x00R\n" +
	"preRelease\x88\x01\x01B\x0e\n" +
	"\f_pre_release\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x16\n" +
	"\x14_service_descriptionB\r\n" +
	"\v_service_idB\t\n" +
	"\a_branchB\t\n" +
	"\a_commitB\r\n" +
	"\v_build_tagsB\x10\n" +
	"\x0e_proto_versionB\f\n" +
	"\n" +
	"_leader_idB\r\n" +
	"\v_start_timeB\t\n" +
	"\a_uptimeB]\n" +
	"\x19io.altessa.serviceinfo.v1P\x01Z>github.com/altessa-s/proto-gen-go/serviceinfo/v1;serviceinfov1b\x06proto3"

var (
	file_serviceinfo_v1_serviceinfo_proto_rawDescOnce sync.Once
	file_serviceinfo_v1_serviceinfo_proto_rawDescData []byte
)

func file_serviceinfo_v1_serviceinfo_proto_rawDescGZIP() []byte {
	file_serviceinfo_v1_serviceinfo_proto_rawDescOnce.Do(func() {
		file_serviceinfo_v1_serviceinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviceinfo_v1_serviceinfo_proto_rawDesc), len(file_serviceinfo_v1_serviceinfo_proto_rawDesc)))
	})
	return file_serviceinfo_v1_serviceinfo_proto_rawDescData
}

var file_serviceinfo_v1_serviceinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_serviceinfo_v1_serviceinfo_proto_goTypes = []any{
	(*ServiceInfo)(nil),                 // 0: io.altessa.serviceinfo.v1.ServiceInfo
	(*ServiceInfo_SemanticVersion)(nil), // 1: io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion
	nil,                                 // 2: io.altessa.serviceinfo.v1.ServiceInfo.MetadataEntry
}
var file_serviceinfo_v1_serviceinfo_proto_depIdxs = []int32{
	1, // 0: io.altessa.serviceinfo.v1.ServiceInfo.semantic_version:type_name -> io.altessa.serviceinfo.v1.ServiceInfo.SemanticVersion
	2, // 1: io.altessa.serviceinfo.v1.ServiceInfo.metadata:type_name -> io.altessa.serviceinfo.v1.ServiceInfo.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_serviceinfo_v1_serviceinfo_proto_init() }
func file_serviceinfo_v1_serviceinfo_proto_init() {
	if File_serviceinfo_v1_serviceinfo_proto != nil {
		return
	}
	file_serviceinfo_v1_serviceinfo_proto_msgTypes[0].OneofWrappers = []any{}
	file_serviceinfo_v1_serviceinfo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviceinfo_v1_serviceinfo_proto_rawDesc), len(file_serviceinfo_v1_serviceinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_serviceinfo_v1_serviceinfo_proto_goTypes,
		DependencyIndexes: file_serviceinfo_v1_serviceinfo_proto_depIdxs,
		MessageInfos:      file_serviceinfo_v1_serviceinfo_proto_msgTypes,
	}.Build()
	File_serviceinfo_v1_serviceinfo_proto = out.File
	file_serviceinfo_v1_serviceinfo_proto_goTypes = nil
	file_serviceinfo_v1_serviceinfo_proto_depIdxs = nil
}
