// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/type/v1/contact.proto

package typev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	phone_number "google.golang.org/genproto/googleapis/type/phone_number"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single contact endpoint (phone, email, social handle, …). The variant
// of `value` carries both the payload and the category — consumers
// dispatch on the oneof case instead of inspecting a separate type tag.
// Phone numbers use google.type.PhoneNumber so country code and extension
// are preserved structurally; email and social handles are opaque strings
// whose format is not enforced by this schema.
type Contact struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier of the contact within its issuing system. Opaque to
	// consumers; used to address this contact in per-element operations on
	// parent messages (e.g. updating one entry in a `repeated Contact` list
	// without replacing the whole list). Assigned at creation and never
	// changes afterwards — to "rename" a contact, delete and recreate it.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The contact endpoint. Exactly one variant MUST be set; an unset
	// `value` is a malformed Contact and producers SHOULD reject it.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Contact_Email
	//	*Contact_Phone
	//	*Contact_SocialHandle
	Value         isContact_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_io_altessa_type_v1_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_type_v1_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_contact_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Contact) GetValue() isContact_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Contact) GetEmail() string {
	if x != nil {
		if x, ok := x.Value.(*Contact_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *Contact) GetPhone() *phone_number.PhoneNumber {
	if x != nil {
		if x, ok := x.Value.(*Contact_Phone); ok {
			return x.Phone
		}
	}
	return nil
}

func (x *Contact) GetSocialHandle() string {
	if x != nil {
		if x, ok := x.Value.(*Contact_SocialHandle); ok {
			return x.SocialHandle
		}
	}
	return ""
}

type isContact_Value interface {
	isContact_Value()
}

type Contact_Email struct {
	// Email address.
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type Contact_Phone struct {
	// Telephone number with structured country code, extension, and
	// short-code support.
	Phone *phone_number.PhoneNumber `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

type Contact_SocialHandle struct {
	// Social media handle (e.g. "@alice" on a network identified
	// out-of-band).
	SocialHandle string `protobuf:"bytes,4,opt,name=social_handle,json=socialHandle,proto3,oneof"`
}

func (*Contact_Email) isContact_Value() {}

func (*Contact_Phone) isContact_Value() {}

func (*Contact_SocialHandle) isContact_Value() {}

var File_io_altessa_type_v1_contact_proto protoreflect.FileDescriptor

var file_io_altessa_type_v1_contact_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x63, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42,
	0x03, 0xe0, 0x41, 0x08, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x12, 0x30, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x25, 0x0a, 0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x6c, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x61, 0x0a, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63,
	0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61,
	0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74,
	0x79, 0x70, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_type_v1_contact_proto_rawDescOnce sync.Once
	file_io_altessa_type_v1_contact_proto_rawDescData []byte
)

func file_io_altessa_type_v1_contact_proto_rawDescGZIP() []byte {
	file_io_altessa_type_v1_contact_proto_rawDescOnce.Do(func() {
		file_io_altessa_type_v1_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_contact_proto_rawDesc), len(file_io_altessa_type_v1_contact_proto_rawDesc)))
	})
	return file_io_altessa_type_v1_contact_proto_rawDescData
}

var file_io_altessa_type_v1_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_io_altessa_type_v1_contact_proto_goTypes = []any{
	(*Contact)(nil),                  // 0: io.altessa.type.v1.Contact
	(*phone_number.PhoneNumber)(nil), // 1: google.type.PhoneNumber
}
var file_io_altessa_type_v1_contact_proto_depIdxs = []int32{
	1, // 0: io.altessa.type.v1.Contact.phone:type_name -> google.type.PhoneNumber
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_io_altessa_type_v1_contact_proto_init() }
func file_io_altessa_type_v1_contact_proto_init() {
	if File_io_altessa_type_v1_contact_proto != nil {
		return
	}
	file_io_altessa_type_v1_contact_proto_msgTypes[0].OneofWrappers = []any{
		(*Contact_Email)(nil),
		(*Contact_Phone)(nil),
		(*Contact_SocialHandle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_contact_proto_rawDesc), len(file_io_altessa_type_v1_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_io_altessa_type_v1_contact_proto_goTypes,
		DependencyIndexes: file_io_altessa_type_v1_contact_proto_depIdxs,
		MessageInfos:      file_io_altessa_type_v1_contact_proto_msgTypes,
	}.Build()
	File_io_altessa_type_v1_contact_proto = out.File
	file_io_altessa_type_v1_contact_proto_goTypes = nil
	file_io_altessa_type_v1_contact_proto_depIdxs = nil
}
