// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/type/v1/date_period.proto

package typev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A calendar-date range, inclusive on both ends. Use this for ranges that
// have no wall-clock component (billing periods, leave windows, …);
// use google.type.Interval for ranges defined by absolute timestamps.
//
// Producers MUST ensure `end_date >= start_date`. A zero-length period
// (start == end) is a valid one-day range. Consumers SHOULD reject
// requests that violate the ordering invariant with INVALID_ARGUMENT.
//
// `google.type.Date` permits partially-specified values (year-only,
// year + month, …). `DatePeriod` requires BOTH bounds to be fully
// specified — non-zero `year`, `month`, and `day` — so consumers can
// do calendar arithmetic without ambiguity. Producers SHOULD reject
// partial dates before constructing a `DatePeriod`.
//
// Timezone: `google.type.Date` is timezone-naive by design. The
// surrounding domain decides how to interpret it (e.g. "the billing
// month in the merchant's local tz"). Do not attach timezone state to
// a `DatePeriod` via a side-channel — if you need timezone-aware
// ranges, use `google.type.Interval` instead.
type DatePeriod struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start date, inclusive.
	StartDate *date.Date `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// End date, inclusive. MUST be on or after start_date.
	EndDate       *date.Date `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatePeriod) Reset() {
	*x = DatePeriod{}
	mi := &file_io_altessa_type_v1_date_period_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatePeriod) ProtoMessage() {}

func (x *DatePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_type_v1_date_period_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatePeriod.ProtoReflect.Descriptor instead.
func (*DatePeriod) Descriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_date_period_proto_rawDescGZIP(), []int{0}
}

func (x *DatePeriod) GetStartDate() *date.Date {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *DatePeriod) GetEndDate() *date.Date {
	if x != nil {
		return x.EndDate
	}
	return nil
}

var File_io_altessa_type_v1_date_period_proto protoreflect.FileDescriptor

var file_io_altessa_type_v1_date_period_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73,
	0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x42, 0x03, 0xe0,
	0x41, 0x02, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x42, 0x53, 0x0a, 0x12, 0x69,
	0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73,
	0x61, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_type_v1_date_period_proto_rawDescOnce sync.Once
	file_io_altessa_type_v1_date_period_proto_rawDescData []byte
)

func file_io_altessa_type_v1_date_period_proto_rawDescGZIP() []byte {
	file_io_altessa_type_v1_date_period_proto_rawDescOnce.Do(func() {
		file_io_altessa_type_v1_date_period_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_date_period_proto_rawDesc), len(file_io_altessa_type_v1_date_period_proto_rawDesc)))
	})
	return file_io_altessa_type_v1_date_period_proto_rawDescData
}

var file_io_altessa_type_v1_date_period_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_io_altessa_type_v1_date_period_proto_goTypes = []any{
	(*DatePeriod)(nil), // 0: io.altessa.type.v1.DatePeriod
	(*date.Date)(nil),  // 1: google.type.Date
}
var file_io_altessa_type_v1_date_period_proto_depIdxs = []int32{
	1, // 0: io.altessa.type.v1.DatePeriod.start_date:type_name -> google.type.Date
	1, // 1: io.altessa.type.v1.DatePeriod.end_date:type_name -> google.type.Date
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_io_altessa_type_v1_date_period_proto_init() }
func file_io_altessa_type_v1_date_period_proto_init() {
	if File_io_altessa_type_v1_date_period_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_date_period_proto_rawDesc), len(file_io_altessa_type_v1_date_period_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_io_altessa_type_v1_date_period_proto_goTypes,
		DependencyIndexes: file_io_altessa_type_v1_date_period_proto_depIdxs,
		MessageInfos:      file_io_altessa_type_v1_date_period_proto_msgTypes,
	}.Build()
	File_io_altessa_type_v1_date_period_proto = out.File
	file_io_altessa_type_v1_date_period_proto_goTypes = nil
	file_io_altessa_type_v1_date_period_proto_depIdxs = nil
}
