// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/type/v1/file_ref.proto

package typev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reference to a file held in an external system (object storage, CDN, …).
// Carries enough information to retrieve the file and describe it for
// display. The schema is intentionally storage-agnostic — neither bucket
// nor backend is encoded here.
type FileRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL for accessing the file. MAY be permanent or a time-limited signed
	// URL — readers must not cache it beyond the lifetime granted by the
	// issuer.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Stable identifier of the file in the issuing system. Opaque to
	// consumers; suitable for re-requesting a fresh URL. Assigned at
	// upload time and never changes afterwards.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// File metadata, when known.
	Metadata      *FileRef_Metadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_io_altessa_type_v1_file_ref_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_type_v1_file_ref_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_file_ref_proto_rawDescGZIP(), []int{0}
}

func (x *FileRef) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileRef) GetMetadata() *FileRef_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Technical descriptors of the referenced file. Producers SHOULD populate
// every field they know; consumers MUST tolerate missing values
// (e.g. legacy records, third-party uploads without inspection).
type FileRef_Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IANA media type of the file content (RFC 6838), e.g. "image/png",
	// "application/pdf", "text/plain".
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// Size of the file in bytes. Negative values are not meaningful.
	SizeBytes int64 `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Original filename including extension, e.g. "report.pdf",
	// "photo.jpg". Not guaranteed to be unique within the storage backend.
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	// Free-form key/value pairs for caller-defined attributes (checksums,
	// alt text, source system, …).
	Custom        map[string]string `protobuf:"bytes,4,rep,name=custom,proto3" json:"custom,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef_Metadata) Reset() {
	*x = FileRef_Metadata{}
	mi := &file_io_altessa_type_v1_file_ref_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef_Metadata) ProtoMessage() {}

func (x *FileRef_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_type_v1_file_ref_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef_Metadata.ProtoReflect.Descriptor instead.
func (*FileRef_Metadata) Descriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_file_ref_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FileRef_Metadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileRef_Metadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *FileRef_Metadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRef_Metadata) GetCustom() map[string]string {
	if x != nil {
		return x.Custom
	}
	return nil
}

var File_io_altessa_type_v1_file_ref_proto protoreflect.FileDescriptor

var file_io_altessa_type_v1_file_ref_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe1, 0x02, 0x0a, 0x07, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x66, 0x12, 0x15, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x13, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x03, 0xe0, 0x41, 0x08, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x40, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x24, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x66, 0x2e,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0xe7, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12,
	0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x69, 0x7a, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x69, 0x7a, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x48, 0x0a, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74,
	0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c,
	0x65, 0x52, 0x65, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x61, 0x0a, 0x12,
	0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x76, 0x31, 0x42, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x66, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_type_v1_file_ref_proto_rawDescOnce sync.Once
	file_io_altessa_type_v1_file_ref_proto_rawDescData []byte
)

func file_io_altessa_type_v1_file_ref_proto_rawDescGZIP() []byte {
	file_io_altessa_type_v1_file_ref_proto_rawDescOnce.Do(func() {
		file_io_altessa_type_v1_file_ref_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_file_ref_proto_rawDesc), len(file_io_altessa_type_v1_file_ref_proto_rawDesc)))
	})
	return file_io_altessa_type_v1_file_ref_proto_rawDescData
}

var file_io_altessa_type_v1_file_ref_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_io_altessa_type_v1_file_ref_proto_goTypes = []any{
	(*FileRef)(nil),          // 0: io.altessa.type.v1.FileRef
	(*FileRef_Metadata)(nil), // 1: io.altessa.type.v1.FileRef.Metadata
	nil,                      // 2: io.altessa.type.v1.FileRef.Metadata.CustomEntry
}
var file_io_altessa_type_v1_file_ref_proto_depIdxs = []int32{
	1, // 0: io.altessa.type.v1.FileRef.metadata:type_name -> io.altessa.type.v1.FileRef.Metadata
	2, // 1: io.altessa.type.v1.FileRef.Metadata.custom:type_name -> io.altessa.type.v1.FileRef.Metadata.CustomEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_io_altessa_type_v1_file_ref_proto_init() }
func file_io_altessa_type_v1_file_ref_proto_init() {
	if File_io_altessa_type_v1_file_ref_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_file_ref_proto_rawDesc), len(file_io_altessa_type_v1_file_ref_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_io_altessa_type_v1_file_ref_proto_goTypes,
		DependencyIndexes: file_io_altessa_type_v1_file_ref_proto_depIdxs,
		MessageInfos:      file_io_altessa_type_v1_file_ref_proto_msgTypes,
	}.Build()
	File_io_altessa_type_v1_file_ref_proto = out.File
	file_io_altessa_type_v1_file_ref_proto_goTypes = nil
	file_io_altessa_type_v1_file_ref_proto_depIdxs = nil
}
