// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/type/v1/gender.proto

package typev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Biological sex of a person. Intentionally minimal — extend the schema in
// downstream code if richer gender identity is needed (this enum stays
// stable and small so it can be reused across unrelated services).
//
// Stability (AIP-180): closed and frozen at v1. New values are NOT
// expected; consumers MAY assume the value set will not grow.
type Gender int32

const (
	// Sentinel default. Treat as "not provided" rather than as a value.
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_io_altessa_type_v1_gender_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_io_altessa_type_v1_gender_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_gender_proto_rawDescGZIP(), []int{0}
}

var File_io_altessa_type_v1_gender_proto protoreflect.FileDescriptor

var file_io_altessa_type_v1_gender_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x2e, 0x76, 0x31, 0x2a, 0x44, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x12, 0x47, 0x45, 0x4e, 0x44, 0x45, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x47, 0x45, 0x4e, 0x44, 0x45,
	0x52, 0x5f, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x45, 0x4e, 0x44,
	0x45, 0x52, 0x5f, 0x46, 0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x02, 0x42, 0x60, 0x0a, 0x12, 0x69,
	0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76,
	0x31, 0x42, 0x0b, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x74,
	0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65, 0x6e,
	0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_type_v1_gender_proto_rawDescOnce sync.Once
	file_io_altessa_type_v1_gender_proto_rawDescData []byte
)

func file_io_altessa_type_v1_gender_proto_rawDescGZIP() []byte {
	file_io_altessa_type_v1_gender_proto_rawDescOnce.Do(func() {
		file_io_altessa_type_v1_gender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_gender_proto_rawDesc), len(file_io_altessa_type_v1_gender_proto_rawDesc)))
	})
	return file_io_altessa_type_v1_gender_proto_rawDescData
}

var file_io_altessa_type_v1_gender_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_io_altessa_type_v1_gender_proto_goTypes = []any{
	(Gender)(0), // 0: io.altessa.type.v1.Gender
}
var file_io_altessa_type_v1_gender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_io_altessa_type_v1_gender_proto_init() }
func file_io_altessa_type_v1_gender_proto_init() {
	if File_io_altessa_type_v1_gender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_gender_proto_rawDesc), len(file_io_altessa_type_v1_gender_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_io_altessa_type_v1_gender_proto_goTypes,
		DependencyIndexes: file_io_altessa_type_v1_gender_proto_depIdxs,
		EnumInfos:         file_io_altessa_type_v1_gender_proto_enumTypes,
	}.Build()
	File_io_altessa_type_v1_gender_proto = out.File
	file_io_altessa_type_v1_gender_proto_goTypes = nil
	file_io_altessa_type_v1_gender_proto_depIdxs = nil
}
