// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/type/v1/location_privacy.proto

package typev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Privacy level applied to a user's geolocation before it is exposed to
// other users or downstream services. The actor that holds raw coordinates
// is expected to coarsen them according to this enum before propagation.
//
// The schema only mandates the precision tier — the exact coarsening
// method (truncation, round-to-nearest, geohash, k-anonymity bucket,
// …) is the producer's choice. Producers SHOULD pick one method and
// apply it deterministically per user, so the user's exposed position
// does not jitter between requests with no real-world movement (this
// would otherwise leak the true position via averaging).
//
// Stability (AIP-180): closed and frozen at v1. New values are NOT
// expected; new precision tiers belong in domain-specific schemas
// rather than as additions here.
type LocationPrivacy int32

const (
	// Sentinel default. When received from a client in a request, servers
	// SHOULD reject with INVALID_ARGUMENT so the privacy choice is
	// explicit. When read from persistent storage, servers SHOULD apply
	// the most restrictive interpretation (= treat as LOCATION_PRIVACY_OFF).
	LocationPrivacy_LOCATION_PRIVACY_UNSPECIFIED LocationPrivacy = 0
	// Tracking disabled. Coordinates must not be persisted.
	LocationPrivacy_LOCATION_PRIVACY_OFF LocationPrivacy = 1
	// Coordinates are persisted but not exposed to other users. The owner can
	// search relative to their own position; they remain non-discoverable to
	// peers.
	LocationPrivacy_LOCATION_PRIVACY_PRIVATE LocationPrivacy = 2
	// City-scale precision: coordinates rounded to ~10 km (≈ 0.1°).
	LocationPrivacy_LOCATION_PRIVACY_PUBLIC_CITY LocationPrivacy = 3
	// Neighbourhood-scale precision: coordinates rounded to ~1 km (≈ 0.01°).
	LocationPrivacy_LOCATION_PRIVACY_PUBLIC_APPROXIMATE LocationPrivacy = 4
	// Full precision (~10 m). Coordinates are exposed as captured.
	LocationPrivacy_LOCATION_PRIVACY_PUBLIC_EXACT LocationPrivacy = 5
)

// Enum value maps for LocationPrivacy.
var (
	LocationPrivacy_name = map[int32]string{
		0: "LOCATION_PRIVACY_UNSPECIFIED",
		1: "LOCATION_PRIVACY_OFF",
		2: "LOCATION_PRIVACY_PRIVATE",
		3: "LOCATION_PRIVACY_PUBLIC_CITY",
		4: "LOCATION_PRIVACY_PUBLIC_APPROXIMATE",
		5: "LOCATION_PRIVACY_PUBLIC_EXACT",
	}
	LocationPrivacy_value = map[string]int32{
		"LOCATION_PRIVACY_UNSPECIFIED":        0,
		"LOCATION_PRIVACY_OFF":                1,
		"LOCATION_PRIVACY_PRIVATE":            2,
		"LOCATION_PRIVACY_PUBLIC_CITY":        3,
		"LOCATION_PRIVACY_PUBLIC_APPROXIMATE": 4,
		"LOCATION_PRIVACY_PUBLIC_EXACT":       5,
	}
)

func (x LocationPrivacy) Enum() *LocationPrivacy {
	p := new(LocationPrivacy)
	*p = x
	return p
}

func (x LocationPrivacy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocationPrivacy) Descriptor() protoreflect.EnumDescriptor {
	return file_io_altessa_type_v1_location_privacy_proto_enumTypes[0].Descriptor()
}

func (LocationPrivacy) Type() protoreflect.EnumType {
	return &file_io_altessa_type_v1_location_privacy_proto_enumTypes[0]
}

func (x LocationPrivacy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocationPrivacy.Descriptor instead.
func (LocationPrivacy) EnumDescriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_location_privacy_proto_rawDescGZIP(), []int{0}
}

var File_io_altessa_type_v1_location_privacy_proto protoreflect.FileDescriptor

var file_io_altessa_type_v1_location_privacy_proto_rawDesc = string([]byte{
	0x0a, 0x29, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e,
	0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x2a,
	0xd9, 0x01, 0x0a, 0x0f, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x63, 0x79, 0x12, 0x20, 0x0a, 0x1c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x50, 0x52, 0x49, 0x56, 0x41, 0x43, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x50, 0x52, 0x49, 0x56, 0x41, 0x43, 0x59, 0x5f, 0x4f, 0x46, 0x46, 0x10, 0x01, 0x12,
	0x1c, 0x0a, 0x18, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x49, 0x56,
	0x41, 0x43, 0x59, 0x5f, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12, 0x20, 0x0a,
	0x1c, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x49, 0x56, 0x41, 0x43,
	0x59, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x43, 0x49, 0x54, 0x59, 0x10, 0x03, 0x12,
	0x27, 0x0a, 0x23, 0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x49, 0x56,
	0x41, 0x43, 0x59, 0x5f, 0x50, 0x55, 0x42, 0x4c, 0x49, 0x43, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f,
	0x58, 0x49, 0x4d, 0x41, 0x54, 0x45, 0x10, 0x04, 0x12, 0x21, 0x0a, 0x1d, 0x4c, 0x4f, 0x43, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x52, 0x49, 0x56, 0x41, 0x43, 0x59, 0x5f, 0x50, 0x55, 0x42,
	0x4c, 0x49, 0x43, 0x5f, 0x45, 0x58, 0x41, 0x43, 0x54, 0x10, 0x05, 0x42, 0x53, 0x0a, 0x12, 0x69,
	0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73,
	0x61, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_type_v1_location_privacy_proto_rawDescOnce sync.Once
	file_io_altessa_type_v1_location_privacy_proto_rawDescData []byte
)

func file_io_altessa_type_v1_location_privacy_proto_rawDescGZIP() []byte {
	file_io_altessa_type_v1_location_privacy_proto_rawDescOnce.Do(func() {
		file_io_altessa_type_v1_location_privacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_location_privacy_proto_rawDesc), len(file_io_altessa_type_v1_location_privacy_proto_rawDesc)))
	})
	return file_io_altessa_type_v1_location_privacy_proto_rawDescData
}

var file_io_altessa_type_v1_location_privacy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_io_altessa_type_v1_location_privacy_proto_goTypes = []any{
	(LocationPrivacy)(0), // 0: io.altessa.type.v1.LocationPrivacy
}
var file_io_altessa_type_v1_location_privacy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_io_altessa_type_v1_location_privacy_proto_init() }
func file_io_altessa_type_v1_location_privacy_proto_init() {
	if File_io_altessa_type_v1_location_privacy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_location_privacy_proto_rawDesc), len(file_io_altessa_type_v1_location_privacy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_io_altessa_type_v1_location_privacy_proto_goTypes,
		DependencyIndexes: file_io_altessa_type_v1_location_privacy_proto_depIdxs,
		EnumInfos:         file_io_altessa_type_v1_location_privacy_proto_enumTypes,
	}.Build()
	File_io_altessa_type_v1_location_privacy_proto = out.File
	file_io_altessa_type_v1_location_privacy_proto_goTypes = nil
	file_io_altessa_type_v1_location_privacy_proto_depIdxs = nil
}
