// Copyright 2026 Altessa Solutions Inc. All rights reserved.
// Use of this source code is governed by license that can be found in
// the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        (unknown)
// source: io/altessa/type/v1/money_range.proto

package typev1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Inclusive range between two monetary amounts. Both bounds MUST share
// the same `currency_code` and `min` MUST NOT exceed `max`; producers
// are responsible for enforcing both invariants. A zero-length range
// (`min == max`) is valid and represents a single amount.
//
// `MoneyRange` has no notion of open or half-open ranges — both bounds
// are required. For one-sided thresholds ("amounts above $100",
// "amounts up to $1000"), use a single `google.type.Money` on the
// surrounding message instead of synthesising a sentinel `min` / `max`.
//
// Negative amounts are permitted (credits, refunds, signed P&L). The
// ordering invariant still applies: `min <= max` as signed values
// (e.g. min = -100, max = -10 is well-formed; min = -10, max = -100 is
// not).
type MoneyRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lower bound, inclusive.
	Min *money.Money `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	// Upper bound, inclusive. MUST be in the same currency as `min` and
	// greater than or equal to `min`.
	Max           *money.Money `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyRange) Reset() {
	*x = MoneyRange{}
	mi := &file_io_altessa_type_v1_money_range_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyRange) ProtoMessage() {}

func (x *MoneyRange) ProtoReflect() protoreflect.Message {
	mi := &file_io_altessa_type_v1_money_range_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyRange.ProtoReflect.Descriptor instead.
func (*MoneyRange) Descriptor() ([]byte, []int) {
	return file_io_altessa_type_v1_money_range_proto_rawDescGZIP(), []int{0}
}

func (x *MoneyRange) GetMin() *money.Money {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *MoneyRange) GetMax() *money.Money {
	if x != nil {
		return x.Max
	}
	return nil
}

var File_io_altessa_type_v1_money_range_proto protoreflect.FileDescriptor

var file_io_altessa_type_v1_money_range_proto_rawDesc = string([]byte{
	0x0a, 0x24, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x69, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x65, 0x73,
	0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0a, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x29, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x42, 0x03,
	0xe0, 0x41, 0x02, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x64, 0x0a, 0x12, 0x69, 0x6f, 0x2e, 0x61,
	0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0f,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c,
	0x74, 0x65, 0x73, 0x73, 0x61, 0x2d, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x69, 0x6f, 0x2f, 0x61, 0x6c, 0x74, 0x65, 0x73, 0x73, 0x61, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_io_altessa_type_v1_money_range_proto_rawDescOnce sync.Once
	file_io_altessa_type_v1_money_range_proto_rawDescData []byte
)

func file_io_altessa_type_v1_money_range_proto_rawDescGZIP() []byte {
	file_io_altessa_type_v1_money_range_proto_rawDescOnce.Do(func() {
		file_io_altessa_type_v1_money_range_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_money_range_proto_rawDesc), len(file_io_altessa_type_v1_money_range_proto_rawDesc)))
	})
	return file_io_altessa_type_v1_money_range_proto_rawDescData
}

var file_io_altessa_type_v1_money_range_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_io_altessa_type_v1_money_range_proto_goTypes = []any{
	(*MoneyRange)(nil),  // 0: io.altessa.type.v1.MoneyRange
	(*money.Money)(nil), // 1: google.type.Money
}
var file_io_altessa_type_v1_money_range_proto_depIdxs = []int32{
	1, // 0: io.altessa.type.v1.MoneyRange.min:type_name -> google.type.Money
	1, // 1: io.altessa.type.v1.MoneyRange.max:type_name -> google.type.Money
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_io_altessa_type_v1_money_range_proto_init() }
func file_io_altessa_type_v1_money_range_proto_init() {
	if File_io_altessa_type_v1_money_range_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_io_altessa_type_v1_money_range_proto_rawDesc), len(file_io_altessa_type_v1_money_range_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_io_altessa_type_v1_money_range_proto_goTypes,
		DependencyIndexes: file_io_altessa_type_v1_money_range_proto_depIdxs,
		MessageInfos:      file_io_altessa_type_v1_money_range_proto_msgTypes,
	}.Build()
	File_io_altessa_type_v1_money_range_proto = out.File
	file_io_altessa_type_v1_money_range_proto_goTypes = nil
	file_io_altessa_type_v1_money_range_proto_depIdxs = nil
}
